CREATE TABLE project (
_id INTEGER PRIMARY KEY AUTOINCREMENT,
PROJECTNAME TEXT NOT NULL,
PROJECTDUEDATE TEXT,
CATEGORY TEXT,
STATUS TEXT,
PRIORITY INTEGER,
INVESTOR_ID INTEGER,
CUSTOMER_ID INTEGER);

CREATE TABLE authorization (
_id INTEGER PRIMARY KEY AUTOINCREMENT,
LOGIN BLOB,
SALT TEXT,
PASSWORD BLOB);

CREATE TABLE employee (
_id INTEGER PRIMARY KEY AUTOINCREMENT,
LASTNAME TEXT,
FIRSTNAME TEXT,
MIDDLENAME TEXT,
EMAIL TEXT,
SKYPE TEXT,
PHONE TEXT,
BIRTHDAY TEXT,
experience TEXT,
education TEXT,
INFO TEXT);


CREATE TABLE customer_investor (
_id INTEGER PRIMARY KEY AUTOINCREMENT,
HANDLE_INV INTEGER,
HANDLE_CUST INTEGER,
LASTNAME TEXT,
FIRSTNAME TEXT,
MIDDLENAME TEXT,
EMAIL TEXT,
SKYPE TEXT,
PHONE TEXT,
COMPANY TEXT,
INFO TEXT);